"""add_shares_to_portfolio_assets

Revision ID: d638b662ac2c
Revises: 97df65538570
Create Date: 2026-04-18 04:04:01.911608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd638b662ac2c'
down_revision: Union[str, None] = '97df65538570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_assets', sa.Column('shares', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_assets', 'shares')
    # ### end Alembic commands ###
